name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anywidget
  - awscli
  - backoff
  - boto3
  - cython
  - earthengine-api
  - fsspec
  - gdal
  - geopandas
  - groff
  - h5py
  - hdf5
  - httpx
  - hvplot
  - isce3=0.22.1
  - lonboard
  - mapclassify
  - matplotlib
  - mpl-scatter-density
  - numba
  - numpy
  - pandas
  - pycurl
  - pyogrio
  - pyOpenSSL=23.1.0
  - pyproj
  - pystac-client
  - python
  - rasterio
  - rasterstats
  - requests
  - rio-cogeo
  - rtree
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sliderule
  - statsmodels
  - tqdm
  - unidecode
  - unzip
  - xmltodict
  - xarray
  - pip=24.2
  - pip:
    - rio-tiler==6.7.0
    - git+https://github.com/MAAP-Project/maap-py.git@v4.1.0