name: vanilla
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli=2.14.1
  - backoff=2.2.1
  - basemap=1.3.7
  - boto3=1.34.41
  - cython=3.0.7
  - earthengine-api=0.1.384
  - gdal=3.7.0
  - geocube=0.4.2
  - geopandas=0.14.2
  - groff=1.22.4
  - h5py=3.9.0
  - hdf5=1.14.0
  - httpx=0.26.0
  - mapclassify=2.6.1
  - matplotlib=3.7.3
  - mizani=0.10.0
  - mpl-scatter-density=0.7
  - numba=0.58.1
  - numpy=1.26.3
  - pandas=2.1.4
  - pandarallel=1.6.5
  - pycurl=7.45.1
  - pygeos=0.14
  - pyogrio=0.6.0
  - pyproj=3.5.0
  - pystac-client=0.7.5
  - python=3.10.13
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - requests=2.31.0
  - rio-cogeo=5.1.1
  - rtree=1.1.0
  - s3fs=2023.12.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.1
  - shapely=2.0.1
  - sliderule=4.1.0
  - statsmodels=0.14.1
  - tqdm=4.66.1
  - unidecode=1.3.7
  - xmltodict=0.13.0
  - pip=23.3.2
  - pip:
    - morecantile==5.1.0
    - rio-tiler==6.2.8