name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - awscli
  - boto3
  - cython
  - gdal
  - geopandas
  - hdf5
  - isce3>=0.25.0
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pycurl
  - pyproj
  #- rasterio
  - requests
  - scikit-learn
  - scipy
  - shapely
  - xarray
  - pip
  - pip:
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6
    - morecantile==6.1.0
    - rio-tiler==7.2.2
    - maap-py==4.2.0
    - maap-algorithms-jupyter-extension==0.3.10
    - maap-jupyter-server-extension==2.1.4
    - maap-dps-jupyter-extension==0.7.6
variables:
  TITILER_STAC_ENDPOINT: 'https://openveda.cloud/api/stac'
  TITILER_ENDPOINT: 'https://openveda.cloud/api/raster'
  STAC_CATALOG_NAME: 'VEDA STAC'
  STAC_CATALOG_URL: 'https://openveda.cloud/api/stac'
  STAC_BROWSER_URL: 'https://openveda.cloud/'
  MAAP_API: 'https://api.maap-project.org/api/'